version: '3.8'

services:
  aws-cli:
    image: raysn0w/aws-cli-alpine:latest
    container_name: aws-cli
    build:
      context: .
      dockerfile: app-dev.dockerfile
      args:
        AWS_CLI_VERSION: 2.7.24
