version: 2.1


jobs:
  build-and-deploy:
    docker:
      - image: cimg/base:2022.08-22.04
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 20.10.14
      - run:
          name: "Building the image"
          command: |
            docker compose build
            echo $DOCKER_HUB | docker login -u $DOCKER_USER --password-stdin
            docker push raysn0w/aws-cli-alpine:latest
            TAG=$(cat docker-compose.yml | yq ".services.aws-cli.build.args.AWS_CLI_VERSION")
            echo "Image Tag: $TAG"
            docker tag raysn0w/aws-cli-alpine:latest raysn0w/aws-cli-alpine:"$TAG"
            docker push raysn0w/aws-cli-alpine:"$TAG"

workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy
